name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  web-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm -ws run lint --if-present
        continue-on-error: true
      - name: Build web
        run: npm --workspace src/web run build
      - name: Upload web artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: src/web/dist
          retention-days: 7

  desktop-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build renderer and electron bundles
        run: npm --workspace src/web run build
        env:
          ELECTRON: '1'
      - name: Package desktop app
        run: npx electron-builder --config electron-builder.yml --publish=never
      - name: Upload desktop artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: desktop-${{ matrix.os }}
          path: |
            dist/*.dmg
            dist/*.exe
            dist/*.AppImage
          retention-days: 7
